### PR TITLE
Locked mongodb to ~1.3.x

### PR DESCRIPTION
**Pull request by james-huston**
clearAndLoad uses functionality that changes in mongodb 2.x, lock to 1.3.x so that things continue to work as expected.

### CODE REVIEW

**Comment by pwaller** [comment]
+1, this would have prevented #19 and saved me and my colleagues a fair amount of pain.

**Comment by igl** [comment]
+1, anyone alive?

**Comment by pwaller** [comment]
Apparently not.

**Comment by pwaller** [comment]
Thanks!

**Comment by chadfawcett** [comment]
@powmedia Can you publish this release to npm?

Since npm hasn't been updated for 2 years, I am having to link directly to the github repo.

`npm install git://github.com/powmedia/pow-mongodb-fixtures.git`

**Comment by pwaller** [comment]
:+1: to what @chadfawcett said

**Comment by igl** [comment]
:+1:

**Comment by powmedia** [comment]
Published as v0.11

**Pull request merged**
