### PR TITLE
Section under API about closing the connection

### PR DESCRIPTION
**Pull request by hugobast**
This personally tripped me up. I couldn't figure out why my jasmine specs we're not exiting properly. I did a little source dive and found the close method's implementation. I think it makes a fine addition to the README.

### CODE REVIEW

**Comment by powmedia** [comment]
Did you fork from master? I've got travis CI checks failing for some reason

**Comment by hugobast** [comment]
I forked from master yes @powmedia. I'll take a look at those failures

**Comment by hugobast** [comment]
I'm looking for `test.done/done` not called according to:

`FAILURES: Undone tests (or their setups/teardowns)`

But nothing is jumping at me.

**Comment by hugobast** [comment]
I just tried locally on 0.12.9 and I did get the error, but I didn't get the error on 0.10.41 like on CI. So there is something there for sure.

**Pull request closed without merging**
